- name: Restart alertmanager
  systemd:
    name: alertmanager
    state: restarted
    daemon_reload: yes

- name: Restart prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
